using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TravelNexus.Services
{
    public static class Airports
    {
      //  private static Dictionary<string, string> AirportCodes;
        public static Dictionary<string, string> AirportCodes { get; set; }


        public static void InitializeAirports()
        {
               AirportCodes = new Dictionary<string, string>();
            AirportCodes.Add("AAL", "Aalborg AMBA");
            AirportCodes.Add("AAR", "Aarhus");
            AirportCodes.Add("ABZ", "Aberdeen Ltd");
            AirportCodes.Add("AUH", "Abu Dhabi");
            AirportCodes.Add("ACA", "Acapulco");
            AirportCodes.Add("ADA", "Adana-Sakirpasa");
            AirportCodes.Add("ADD", "Addis Ababa-Bole");
            AirportCodes.Add("ADL", "Adelaide");
            AirportCodes.Add("ADE", "Aden");
            AirportCodes.Add("POW", "Aerodrom Portoroz doo");
            AirportCodes.Add("AGA", "Agadir - Al Massira");
            AirportCodes.Add("AGF", "Agen - La Garenne");
            AirportCodes.Add("AGR", "Agra");
            AirportCodes.Add("AMD", "Ahmedabad - Sardar Vallabh Bhai Patel Int´l");
            AirportCodes.Add("AJA", "Ajaccio - Campo Dell´Oro");
            AirportCodes.Add("CAK", "Akron-Canton Regional");
            AirportCodes.Add("ALS", "Alamosa-Bergman-San Luis Valley Regional Airfield");
            AirportCodes.Add("ALB", "Albany");
            AirportCodes.Add("LBI", "Albi - Le Sequestre");
            AirportCodes.Add("ABQ", "Albuquerque");
            AirportCodes.Add("ACI", "Alderney");
            AirportCodes.Add("ALP", "Aleppo");
            AirportCodes.Add("AES", "Alesund-Vigra");
            AirportCodes.Add("ESF", "Alexandria");
            AirportCodes.Add("ALY", "Alexandria - El Nhouza");
            AirportCodes.Add("AXD", "Alexandroupolis National");
            AirportCodes.Add("AHO", "Alghero-Fertilia");
            AirportCodes.Add("ALG", "Algiers-Houari Boumedienne");
            AirportCodes.Add("ALC", "Alicante");
            AirportCodes.Add("ASP", "Alice Springs");
            AirportCodes.Add("ALA", "Almaty Int´l");
            AirportCodes.Add("LEI", "Almeria");
            AirportCodes.Add("AOR", "Alor Setar - Sultan Abdul Halim");
            AirportCodes.Add("ACH", "Altenrhein");
            AirportCodes.Add("AMA", "Amarillo - Rick Husband");
            AirportCodes.Add("SID", "Amilcar Cabral");
            AirportCodes.Add("AMM", "Amman-Queen Alia");
            AirportCodes.Add("ATQ", "Amritsar - Raja Sansi");
            AirportCodes.Add("SPL", "Amsterdam Schiphol");
            AirportCodes.Add("ANC", "Anchorage - Ted Stevens");
            AirportCodes.Add("AOI", "Ancona");
            AirportCodes.Add("ANG", "Angoulême - Brie-Champniers");
            AirportCodes.Add("ESB", "Ankara - Esenboga");
            AirportCodes.Add("AAE", "Annaba-Rabah Bitat");
            AirportCodes.Add("NCY", "Annecy - Haute Savoie");
            AirportCodes.Add("AYT", "Antalya");
            AirportCodes.Add("TNR", "Antananarivo-Ivato Aerodrome");
            AirportCodes.Add("SJF", "Antigua-VC Bird");
            AirportCodes.Add("ANF", "Antofagasta-Cerro Moreno");
            AirportCodes.Add("ANR", "Antwerp");
            AirportCodes.Add("ATW", "Appleton/Outagamie County Regional");
            AirportCodes.Add("AQJ", "Aqaba");
            AirportCodes.Add("ARW", "Arad");
            AirportCodes.Add("ARI", "Arica-Chacalluta");
            AirportCodes.Add("ARH", "Arkhangelsk - Talagi");
            AirportCodes.Add("AUA", "Aruba - Queen Beatrix");
            AirportCodes.Add("AVL", "Asheville Regional");
            AirportCodes.Add("ASB", "Ashkabad");
            AirportCodes.Add("ASM", "Asmara Int´l");
            AirportCodes.Add("OVD", "Asturias");
            AirportCodes.Add("ASU", "Asuncion - Silvio Pettirossi");
            AirportCodes.Add("ASW", "Aswan - Daraw");
            AirportCodes.Add("AHN", "Athens Ben Epps");
            AirportCodes.Add("ATH", "Athens");
            AirportCodes.Add("ATL", "Atlanta - Hartsfield Atlanta");
            AirportCodes.Add("ACY", "Atlantic Airport Int´l");
            AirportCodes.Add("AKL", "Auckland");
            AirportCodes.Add("AGB", "Augsburg");
            AirportCodes.Add("AGS", "Augusta Regional");
            AirportCodes.Add("AUS", "Austin-Bergstrom");
            AirportCodes.Add("AVN", "Avignon/Caumont");
            AirportCodes.Add("BJZ", "Badajoz-Talavera la Real");
            AirportCodes.Add("FKB", "Baden-Airpark GmbH");
            AirportCodes.Add("SDA", "Baghdad");
            AirportCodes.Add("BAH", "Bahrain");
            AirportCodes.Add("BAK", "Baku - Bina Int´l");
            AirportCodes.Add("DPS", "Bali-Denpasar-Ngurah Rai");
            AirportCodes.Add("BPN", "Balikpapan-Sepinggan");
            AirportCodes.Add("BWI", "Baltimore/Washington Int´l");
            AirportCodes.Add("BKO", "Bamako-Senou Int´l");
            AirportCodes.Add("CMB", "Bandaranaike Int´l");
            AirportCodes.Add("BLR", "Bangalore");
            AirportCodes.Add("BKK", "Bangkok Int´l");
            AirportCodes.Add("BGR", "Bangor");
            AirportCodes.Add("BGF", "Bangui-M´Poko");
            AirportCodes.Add("BJL", "Banjul Int´l");
            AirportCodes.Add("BWU", "Bankstown");
            AirportCodes.Add("BCN", "Barcelona");
            AirportCodes.Add("BRI", "Bari-Palese");
            AirportCodes.Add("BAX", "Barnaul");
            AirportCodes.Add("BRR", "Barra");
            AirportCodes.Add("BAQ", "Barranquilla-Aeropuerto Int´l Ernesto Cortissoz");
            AirportCodes.Add("MLH", "Basel/Mulhouse");
            AirportCodes.Add("BSL", "Basel/Mulhouse");
            AirportCodes.Add("BTR", "Baton Rouge Metroplitan");
            AirportCodes.Add("BVA", "Beauvais/Tille");
            AirportCodes.Add("PEK", "Beijing - Capital");
            AirportCodes.Add("BEW", "Beira");
            AirportCodes.Add("BEY", "Beirut");
            AirportCodes.Add("BFS", "Belfast");
            AirportCodes.Add("BHD", "Belfast Airport");
            AirportCodes.Add("BEG", "Belgrade");
            AirportCodes.Add("BZE", "Belize-Phillip SW Goldson");
            AirportCodes.Add("BLI", "Bellingham");
            AirportCodes.Add("PLU", "Belo Horizonte - Pampulha");
            AirportCodes.Add("CNF", "Belo Horizonte - Tancredo Neves Int´l");
            AirportCodes.Add("BEB", "Benbecula");
            AirportCodes.Add("BEN", "Benghazi - Benina");
            AirportCodes.Add("BGO", "Bergen, Flesland");
            AirportCodes.Add("EGC", "Bergerac-Roumaniere");
            AirportCodes.Add("SXF", "Berlin - Schönefeld");
            AirportCodes.Add("TXL", "Berlin - Tegel");
            AirportCodes.Add("THF", "Berlin - Tempelhof");
            AirportCodes.Add("BDA", "Bermuda");
            AirportCodes.Add("BRN", "Bern");
            AirportCodes.Add("BZR", "Beziers/Vias");
            AirportCodes.Add("BIK", "Biak-Frans Kaisiepo");
            AirportCodes.Add("BIQ", "Biarritz/Bayone/Anglet");
            AirportCodes.Add("BIO", "Bilbao");
            AirportCodes.Add("BIL", "Billings Logan");
            AirportCodes.Add("BLL", "Billund");
            AirportCodes.Add("BGM", "Binghamton");
            AirportCodes.Add("BTU", "Bintulu");
            AirportCodes.Add("BHX", "Birmingham");
            AirportCodes.Add("BHM", "Birmingham");
            AirportCodes.Add("KGA", "Bishkek-Manas");
            AirportCodes.Add("BIS", "Bismark Municipal");
            AirportCodes.Add("BXO", "Bissau-Osvaldo Vieira");
            AirportCodes.Add("BBS", "Blackbushe");
            AirportCodes.Add("BLK", "Blackpool");
            AirportCodes.Add("BLZ", "Blantyre-Chileka");
            AirportCodes.Add("BFN", "Bloemfontein");
            AirportCodes.Add("BLF", "Bluefield - Mercer County");
            AirportCodes.Add("BVB", "Boa Vista Int´l");
            AirportCodes.Add("BOO", "Bodø");
            AirportCodes.Add("BFI", "Boeing Field/King County Int´l");
            AirportCodes.Add("BOG", "Bogotá-El Dorado");
            AirportCodes.Add("BOI", "Boise");
            AirportCodes.Add("BLQ", "Bologna-G Marconi");
            AirportCodes.Add("TRW", "Bonriki Int´l");
            AirportCodes.Add("BOD", "Bordeaux/Merignac");
            AirportCodes.Add("BLE", "Borlänge");
            AirportCodes.Add("RNN", "Bornholm-Roenne");
            AirportCodes.Add("BOS", "Boston-Logan");
            AirportCodes.Add("BOJ", "Bourgas");
            AirportCodes.Add("BOU", "Bourges");
            AirportCodes.Add("BOH", "Bournemouth");
            AirportCodes.Add("BZN", "Bozeman");
            AirportCodes.Add("BFD", "Bradford Regional");
            AirportCodes.Add("BSB", "Brasilia Int´l - Presidente Juscelino Kubitschek");
            AirportCodes.Add("BTS", "Bratislava - M R Stefanik");
            AirportCodes.Add("BVZ", "Brazzaville - Maya Maya");
            AirportCodes.Add("BRE", "Bremen - Flughafen Bremen");
            AirportCodes.Add("BES", "Brest/Guipavas");
            AirportCodes.Add("BDS", "Brindisi");
            AirportCodes.Add("BNE", "Brisbane");
            AirportCodes.Add("BRS", "Bristol");
            AirportCodes.Add("BVE", "Brive - La Roche");
            AirportCodes.Add("BRQ", "Brno-Turany");
            AirportCodes.Add("BRO", "Brownsville/South Padre Island Int´l");
            AirportCodes.Add("BWN", "Brunei-Bandar Seri Begawan");
            AirportCodes.Add("BRU", "Brussels");
            AirportCodes.Add("CRL", "Brussels-South Charleroi");
            AirportCodes.Add("BGA", "Bucaramanga - Palo Negro");
            AirportCodes.Add("BBU", "Bucharest - Baneasa");
            AirportCodes.Add("OTP", "Bucharest - Otopeni");
            AirportCodes.Add("BUD", "Budapest - Ferihegy");
            AirportCodes.Add("EZE", "Buenos Aires - Aeropuerto Ministro Pistarini Int´l Ezeiza");
            AirportCodes.Add("DOT", "Buenos Aires - Don Torcuato");
            AirportCodes.Add("BUF", "Buffalo Niagara Int´l");
            AirportCodes.Add("BJM", "Bujumbura");
            AirportCodes.Add("BUQ", "Bulawayo");
            AirportCodes.Add("BUR", "Burbank-Glendale-Pasedena");
            AirportCodes.Add("BTV", "Burlington");
            AirportCodes.Add("CNS", "Cairns");
            AirportCodes.Add("CAI", "Cairo");
            AirportCodes.Add("YYC", "Calgary");
            AirportCodes.Add("CLO", "Cali-Alfonso Bonilla Aragón");
            AirportCodes.Add("CCI", "Calicut");
            AirportCodes.Add("CLY", "Calvi - Sainte Catherine");
            AirportCodes.Add("CMW", "Camagüey-Ignacio Agramonte");
            AirportCodes.Add("CBG", "Cambridge");
            AirportCodes.Add("CDU", "Camden");
            AirportCodes.Add("CAL", "Campbeltown");
            AirportCodes.Add("CPE", "Campeche - Ingeniero Alberto Acuna Ongay Int´l");
            AirportCodes.Add("CGR", "Campo Grande");
            AirportCodes.Add("CBN", "Canberra");
            AirportCodes.Add("CUN", "Cancun Int´l");
            AirportCodes.Add("DCF", "Canefield");
            AirportCodes.Add("CEQ", "Cannes");
            AirportCodes.Add("CPT", "Cape Town");
            AirportCodes.Add("CCS", "Caracas-Maiquetia Simon Bolivar");
            AirportCodes.Add("CCF", "Carcassonne");
            AirportCodes.Add("CWL", "Cardiff");
            AirportCodes.Add("CAX", "Carlisle");
            AirportCodes.Add("CTG", "Cartagena-Rafael Nunez");
            AirportCodes.Add("CMN", "Casablanca - Mohammed V");
            AirportCodes.Add("CPR", "Casper/Natrona County Int´l");
            AirportCodes.Add("DCM", "Castres - Mazamet");
            AirportCodes.Add("CTA", "Catania-Fontanarossa");
            AirportCodes.Add("CAY", "Cayenne - Rochambeau");
            AirportCodes.Add("CYO", "Cayo Largo-Vilo Acuña Int´l");
            AirportCodes.Add("CMF", "Chambery/Aix les Bains");
            AirportCodes.Add("CMI", "Champaign - Willard");
            AirportCodes.Add("CHQ", "Chania K Daskalogiannis");
            AirportCodes.Add("GCI", "Channel Islands - Guernsey");
            AirportCodes.Add("JER", "Channel Islands - Jersey");
            AirportCodes.Add("CRW", "Charleston-Yeager");
            AirportCodes.Add("CLT", "Charlotte/Douglas Int´l");
            AirportCodes.Add("CHA", "Chattanooga Metropolitan");
            AirportCodes.Add("PAR", "Chavenay");
            AirportCodes.Add("CJU", "Cheju - Jeju");
            AirportCodes.Add("CEK", "Chelyabinsk - Balandino");
            AirportCodes.Add("CTU", "Chengdu/Shuangliu");
            AirportCodes.Add("MAA", "Chennai/Madras - Meenambakam");
            AirportCodes.Add("CER", "Cherbourg-Maupertus");
            AirportCodes.Add("CEG", "Chester");
            AirportCodes.Add("CTM", "Chetumal");
            AirportCodes.Add("CYS", "Cheyenne");
            AirportCodes.Add("CNX", "Chiang Mai Int´l");
            AirportCodes.Add("CEI", "Chiang Rai");
            AirportCodes.Add("MDW", "Chicago Midway");
            AirportCodes.Add("ORD", "Chicago-O´Hare");
            AirportCodes.Add("KIV", "Chisinau");
            AirportCodes.Add("CGP", "Chittagong - Shah Amanat Int´l");
            AirportCodes.Add("CHC", "Christchurch Ltd");
            AirportCodes.Add("CHR", "Châteauroux/Déols-Marcel Dassault");
            AirportCodes.Add("AVI", "Ciego de Avila-Maximo Gomez Int´l");
            AirportCodes.Add("CFG", "Cienfuegos - Jamie González Int´l");
            AirportCodes.Add("CVG", "Cincinnati/N Kentucky Int´l");
            AirportCodes.Add("LDY", "Airport of Derry - Londonderry");
            AirportCodes.Add("CME", "Ciudad del Carmen");
            AirportCodes.Add("CEN", "Ciudad Obregón");
            AirportCodes.Add("CVM", "Ciudad Victoria");
            AirportCodes.Add("CFE", "Clermont Ferrand Auvergne");
            AirportCodes.Add("CLE", "Cleveland - Hopkins");
            AirportCodes.Add("COK", "Cochin");
            AirportCodes.Add("CCK", "Cocos Islands");
            AirportCodes.Add("CJB", "Coimbatore");
            AirportCodes.Add("CLQ", "Colima");
            AirportCodes.Add("CMR", "Colmar-Houssen");
            AirportCodes.Add("CGN", "Cologne/Bonn");
            AirportCodes.Add("COS", "Colorado Springs");
            AirportCodes.Add("CAE", "Columbia Metropolitan");
            AirportCodes.Add("CMH", "Columbus - Port Columbus Int´l");
            AirportCodes.Add("GTR", "Columbus-Golden Triangle Regional");
            AirportCodes.Add("CKY", "Conakry-Gbessia");
            AirportCodes.Add("CCP", "Concepcion");
            AirportCodes.Add("CND", "Constanta-Mihail Kogalniceanu");
            AirportCodes.Add("CZL", "Constantine");
            AirportCodes.Add("RAR", "Cook Is-Rarotonga");
            AirportCodes.Add("OOL", "Coolangatta - Gold Coast");
            AirportCodes.Add("RKE", "Copenhagen Roskilde");
            AirportCodes.Add("CPH", "Copenhagen - Kastrup");
            AirportCodes.Add("ODB", "Cordoba");
            AirportCodes.Add("COR", "Cordoba - Ambrosio l y Taravella");
            AirportCodes.Add("CFU", "Corfu I Kapodistrias");
            AirportCodes.Add("CRK", "Cork");
            AirportCodes.Add("CRP", "Corpus Christi Int´l");
            AirportCodes.Add("CEZ", "Cortez Municipal");
            AirportCodes.Add("CMG", "Corumba");
            AirportCodes.Add("COO", "Cotonou");
            AirportCodes.Add("CVT", "Coventry - West Midlands");
            AirportCodes.Add("CZM", "Cozumel");
            AirportCodes.Add("CRV", "Crotone");
            AirportCodes.Add("TAB", "Crown Point");
            AirportCodes.Add("CZS", "Cruzeiro do Sul Int´l");
            AirportCodes.Add("CVJ", "Cuernavaca");
            AirportCodes.Add("CBE", "Cumberland Regional");
            AirportCodes.Add("CUF", "Cuneo-Levaldigi");
            AirportCodes.Add("CUR", "Curacao - Hato");
            AirportCodes.Add("CWB", "Curitiba - Afonso Pena");
            AirportCodes.Add("DKR", "Dakar-Yoff - Leopol Sedar Senghor Int´l");
            AirportCodes.Add("DLM", "Dalaman");
            AirportCodes.Add("DLC", "Dalian - Zhoushuizi");
            AirportCodes.Add("DAL", "Dallas Love Field");
            AirportCodes.Add("DFW", "Dallas/Fort Worth");
            AirportCodes.Add("DAM", "Damascus");
            AirportCodes.Add("OED", "Dammam - King Fahd");
            AirportCodes.Add("MSN", "Dane County Regional");
            AirportCodes.Add("DAR", "Dar-es-Salaam");
            AirportCodes.Add("DRW", "Darwin Int´l");
            AirportCodes.Add("DVO", "Davao Int´l");
            AirportCodes.Add("DAY", "Dayton");
            AirportCodes.Add("DAB", "Daytona Beach Int´l");
            AirportCodes.Add("DOL", "Deauville/Saint Gatien");
            AirportCodes.Add("DEC", "Decatur");
            AirportCodes.Add("DEL", "Delhi - Indira Ghandi");
            AirportCodes.Add("DEN", "Denver");
            AirportCodes.Add("DSM", "Des Moines");
            AirportCodes.Add("DET", "Detroit Airport");
            AirportCodes.Add("DTW", "Detroit Metropolitan Wayne County");
            AirportCodes.Add("DHA", "Dhahran");
            AirportCodes.Add("DAC", "Dhaka - Zia");
            AirportCodes.Add("DIJ", "Dijon-Bourgogne Aéroport");
            AirportCodes.Add("DNR", "Dinard/Plertuit/St Malo");
            AirportCodes.Add("DJE", "Djerba-Zarzis");
            AirportCodes.Add("JIB", "Djibouti - Ambouli");
            AirportCodes.Add("DNK", "Dnepropetrovsk");
            AirportCodes.Add("DOH", "Doha");
            AirportCodes.Add("DLE", "Dole/Tavaux");
            AirportCodes.Add("CFN", "Donegal Int´l");
            AirportCodes.Add("DTM", "Dortmund - Wickede");
            AirportCodes.Add("DHN", "Dothan Regional");
            AirportCodes.Add("DLA", "Douala");
            AirportCodes.Add("DRS", "Dresden");
            AirportCodes.Add("DXB", "Dubai");
            AirportCodes.Add("DUB", "Dublin");
            AirportCodes.Add("DUJ", "Dubois-Jefferson County");
            AirportCodes.Add("DBV", "Dubrovnik");
            AirportCodes.Add("DBQ", "Dubuque Regional");
            AirportCodes.Add("DND", "Dundee");
            AirportCodes.Add("DUD", "Dunedin Ltd");
            AirportCodes.Add("DRO", "Durango - La Plata County");
            AirportCodes.Add("DUR", "Durban");
            AirportCodes.Add("DYU", "Dushanbe");
            AirportCodes.Add("DUS", "Düsseldorf");
            AirportCodes.Add("MGL", "Düsseldorf Express- Mönchengladbach");
            AirportCodes.Add("ELS", "East London");
            AirportCodes.Add("EMA", "East Midlands");
            AirportCodes.Add("CID", "Eastern Iowa");
            AirportCodes.Add("EDI", "Edinburgh");
            AirportCodes.Add("YEG", "Edmonton");
            AirportCodes.Add("EGS", "Egilsstadir");
            AirportCodes.Add("ETH", "Eilat-J Hozman");
            AirportCodes.Add("EIN", "Eindhoven");
            AirportCodes.Add("SVX", "Ekaterinburg - Koltcovo");
            AirportCodes.Add("ELP", "El Paso");
            AirportCodes.Add("SAL", "El Salvador Int´l");
            AirportCodes.Add("ELM", "Elmira/Coring Regional");
            AirportCodes.Add("ENF", "Enontekiö");
            AirportCodes.Add("ENS", "Enschede Twente");
            AirportCodes.Add("EBB", "Entebbe");
            AirportCodes.Add("EPL", "Epinal/Mirecourt");
            AirportCodes.Add("ERF", "Erfurt");
            AirportCodes.Add("ERI", "Erie");
            AirportCodes.Add("EBJ", "Esbjerg");
            AirportCodes.Add("ESS", "Essen/Mulheim");
            AirportCodes.Add("MEB", "Essendon");
            AirportCodes.Add("EVV", "Evansville Regional");
            AirportCodes.Add("EXT", "Exeter");
            AirportCodes.Add("FAI", "Fairbanks Int´l");
            AirportCodes.Add("APW", "Faleolo");
            AirportCodes.Add("FAR", "Fargo - Hector");
            AirportCodes.Add("FAB", "Farnborough");
            AirportCodes.Add("FAO", "Faro");
            AirportCodes.Add("FYV", "Fayetteville Municipal - Drake Field");
            AirportCodes.Add("FAY", "Fayetteville Regional");
            AirportCodes.Add("FYM", "Fayetteville - Lincoln County Regional");
            AirportCodes.Add("FEZ", "Fes Saiss");
            AirportCodes.Add("SUV", "Fiji - Suva Nausori Int´l");
            AirportCodes.Add("NAN", "Fiji-Nadi");
            AirportCodes.Add("FLG", "Flagstaff Pulliam");
            AirportCodes.Add("BON", "Flamingo");
            AirportCodes.Add("FNT", "Flint - Bishop");
            AirportCodes.Add("FLO", "Florence Regional");
            AirportCodes.Add("FLR", "Florence - Amerigo Vespucci");
            AirportCodes.Add("FLW", "Flores");
            AirportCodes.Add("FRL", "Forli");
            AirportCodes.Add("FNL", "Fort Collins-Loveland Municipal");
            AirportCodes.Add("FLL", "Fort Lauderdale-Hollywood Int´l");
            AirportCodes.Add("YMM", "Fort McMurray");
            AirportCodes.Add("RSW", "Fort Myers-SW Florida Int´l");
            AirportCodes.Add("FPR", "Fort Pierce - St Lucie County Int´l");
            AirportCodes.Add("FSM", "Fort Smith");
            AirportCodes.Add("FWA", "Fort Wayne");
            AirportCodes.Add("FOR", "Fortaleza");
            AirportCodes.Add("IGU", "Foz do Iguaçu-Cataratas Int´l");
            AirportCodes.Add("MVB", "Franceville - Mvengue");
            AirportCodes.Add("FRW", "Francistown");
            AirportCodes.Add("FRA", "Frankfurt");
            AirportCodes.Add("HHN", "Frankfurt-Hahn");
            AirportCodes.Add("FNA", "Freetown-Lunghi");
            AirportCodes.Add("FAT", "Fresno Yosemite");
            AirportCodes.Add("FDH", "Friedrichshafen/Lowental");
            AirportCodes.Add("TBU", "Fua´amotu Int´l");
            AirportCodes.Add("FUE", "Fuerteventura");
            AirportCodes.Add("FJR", "Fujairah");
            AirportCodes.Add("FKJ", "Fukui");
            AirportCodes.Add("FNC", "Funchal -o da Madeira");
            AirportCodes.Add("GBE", "Gaborone-Seretse Khama");
            AirportCodes.Add("GLE", "Gainesville Regional");
            AirportCodes.Add("GWY", "Galway");
            AirportCodes.Add("GOU", "Garoua");
            AirportCodes.Add("GAY", "Gaya");
            AirportCodes.Add("GDN", "Gdansk-Trojmiasto Ltd");
            AirportCodes.Add("DLD", "Geilo - Dagali");
            AirportCodes.Add("GVA", "Geneva");
            AirportCodes.Add("GOA", "Genoa");
            AirportCodes.Add("GRJ", "George");
            AirportCodes.Add("GEO", "Georgetown - Cheddi Jagan Int´l");
            AirportCodes.Add("GRO", "Gerona-Costa Brava");
            AirportCodes.Add("GIB", "Gibraltar");
            AirportCodes.Add("GLA", "Glasgow Ltd");
            AirportCodes.Add("PIK", "Glasgow - Prestwick");
            AirportCodes.Add("GLO", "Gloucestershire");
            AirportCodes.Add("GOI", "Goa - Dabolim");
            AirportCodes.Add("GME", "Gomel (Pokalubichi)");
            AirportCodes.Add("GOZ", "Gorna Orjahovica");
            AirportCodes.Add("LPA", "Gran Canaria");
            AirportCodes.Add("GRX", "Granada");
            AirportCodes.Add("FPO", "Grand Bahama");
            AirportCodes.Add("GCM", "Grand Cayman-Owen Roberts Int´l");
            AirportCodes.Add("GFK", "Grand Forks Int´l");
            AirportCodes.Add("GJT", "Grand Junction - Walker Field");
            AirportCodes.Add("GPZ", "Grand Rapids/Kent County Int´l");
            AirportCodes.Add("GDT", "Grand Turk");
            AirportCodes.Add("SFG", "Grande Case - L´Esperance");
            AirportCodes.Add("MWH", "Grant County");
            AirportCodes.Add("BGI", "Grantley Adams Int´l");
            AirportCodes.Add("GRZ", "Graz");
            AirportCodes.Add("GTF", "Great Falls");
            AirportCodes.Add("RIV", "Greater Los Angeles/March GlobalPort");
            AirportCodes.Add("ROC", "Greater Rochester Int´l");
            AirportCodes.Add("GSP", "Greenville Spartanburg");
            AirportCodes.Add("GND", "Grenada-Point Salines Int´l");
            AirportCodes.Add("GNB", "Grenoble/Saint-Geoirs");
            AirportCodes.Add("GRQ", "Groningen Eelde");
            AirportCodes.Add("GDL", "Guadalajarra-Don Miguel Hidalgo");
            AirportCodes.Add("GUM", "Guam-Antonio BWon Pat Int´l");
            AirportCodes.Add("CAN", "Guangzhou Baiyun");
            AirportCodes.Add("GUA", "Guatemala Airport - La Aurora");
            AirportCodes.Add("GYE", "Guayaquil-Simon Bolivar");
            AirportCodes.Add("GYM", "Guaymas - General Jose Maria Yanez Intl");
            AirportCodes.Add("GPT", "Gulfport - Biloxi");
            AirportCodes.Add("GSE", "Göteborg Airport");
            AirportCodes.Add("GOT", "Göteborg-Landvetter");
            AirportCodes.Add("HGR", "Hagerstown Regional");
            AirportCodes.Add("HFA", "Haifa - U Michaeli");
            AirportCodes.Add("YHZ", "Halifax Stanfield");
            AirportCodes.Add("HAM", "Hamburg");
            AirportCodes.Add("YHM", "Hamilton");
            AirportCodes.Add("HAJ", "Hannover");
            AirportCodes.Add("HAN", "Hanoi - Noi Bai");
            AirportCodes.Add("HRE", "Harare");
            AirportCodes.Add("HRB", "Harbin - Taiping");
            AirportCodes.Add("HAR", "Harrisburg");
            AirportCodes.Add("EVE", "Harstad/Narvik - Evenes");
            AirportCodes.Add("BDL", "Hartford - Springfield - Bradley");
            AirportCodes.Add("HSI", "Hastings Municipal");
            AirportCodes.Add("HDY", "Hat Yai Int´l");
            AirportCodes.Add("HAU", "Haugesund");
            AirportCodes.Add("HAW", "Haverfordwest");
            AirportCodes.Add("HEM", "Helsinki - Malmi");
            AirportCodes.Add("HEL", "Helsinki - Vantaa");
            AirportCodes.Add("HIR", "Henderson");
            AirportCodes.Add("HER", "Heraklion - Nikos Kazantzakis");
            AirportCodes.Add("HKY", "Hickory Regional");
            AirportCodes.Add("VDE", "Hierro");
            AirportCodes.Add("HXD", "Hilton Head Island");
            AirportCodes.Add("HIJ", "Hiroshima");
            AirportCodes.Add("SGN", "Ho Chi Minh Airport - Tan Son Nhat Int´l");
            AirportCodes.Add("HBA", "Hobart");
            AirportCodes.Add("HOG", "Holguin-Frank Pais Int´l");
            AirportCodes.Add("HKG", "Hong Kong (HKG)");
            AirportCodes.Add("HNL", "Honolulu");
            AirportCodes.Add("HOR", "Horta");
            AirportCodes.Add("IAH", "Houston - George Bush Intercontinental");
            AirportCodes.Add("HOU", "Houston - William P Hobby");
            AirportCodes.Add("HUY", "Humberside Ltd");
            AirportCodes.Add("HTS", "Huntington Tri-State");
            AirportCodes.Add("HSV", "Huntsville");
            AirportCodes.Add("HRG", "Hurgadah");
            AirportCodes.Add("HYD", "Hyderabad");
            AirportCodes.Add("IBZ", "Ibiza");
            AirportCodes.Add("IDY", "Ile d´Yeu - Grand Phare");
            AirportCodes.Add("IND", "Indianapolis");
            AirportCodes.Add("INN", "Innsbruck");
            AirportCodes.Add("INV", "Inverness-Dalcross");
            AirportCodes.Add("IYK", "Inyokern - Kern County");
            AirportCodes.Add("IOA", "Ioannina National");
            AirportCodes.Add("IPH", "Ipoh - Sultan Azlan Shah");
            AirportCodes.Add("IQT", "Iquitos");
            AirportCodes.Add("IKT", "Irkutsk");
            AirportCodes.Add("ISB", "Islamabad");
            AirportCodes.Add("ILY", "Islay");
            AirportCodes.Add("IOM", "Isle of Man");
            AirportCodes.Add("ISC", "Isles of Scilly-St Mary´s");
            AirportCodes.Add("IST", "Istanbul - Atatürk");
            AirportCodes.Add("ITH", "Ithaca - Tompkins County");
            AirportCodes.Add("IVL", "Ivalo Int´l");
            AirportCodes.Add("ADB", "Izmir - Adnan Menderes");
            AirportCodes.Add("JAC", "Jackson Hole");
            AirportCodes.Add("JAN", "Jackson Int´l");
            AirportCodes.Add("JAX", "Jacksonville");
            AirportCodes.Add("JAI", "Jaipur - Sanganeer");
            AirportCodes.Add("HLP", "Jakarta - Halim Perdanakusuma Int´l");
            AirportCodes.Add("JKT", "Jakarta - Soekarno Hatta");
            AirportCodes.Add("JED", "Jeddah - King Abdulaziz");
            AirportCodes.Add("FSD", "Sioux Falls");
            AirportCodes.Add("JOE", "Joensuu");
            AirportCodes.Add("JNB", "Johannesburg");
            AirportCodes.Add("JST", "Johnstown - Cambria County");
            AirportCodes.Add("JHB", "Johor Bahru - Sultan Ismail");
            AirportCodes.Add("JYV", "Jyvaskyla");
            AirportCodes.Add("JKJ", "Jönköping");
            AirportCodes.Add("KBL", "Kabul-Khwaja Rawash");
            AirportCodes.Add("KAJ", "Kajaani");
            AirportCodes.Add("AZO", "Kalamazoo/Battle Creek Int´l");
            AirportCodes.Add("KLR", "Kalmar");
            AirportCodes.Add("KAN", "Kano - Mallam Aminu Kano");
            AirportCodes.Add("MCI", "Kansas Airport");
            AirportCodes.Add("MKC", "Kansas Airport Downtown");
            AirportCodes.Add("KHH", "Kaohsiung Int´l");
            AirportCodes.Add("KHI", "Karachi");
            AirportCodes.Add("KGF", "Karaganda - Sary Arka");
            AirportCodes.Add("KAB", "Kariba");
            AirportCodes.Add("KLV", "Karlovy Vary");
            AirportCodes.Add("KGJ", "Karonga");
            AirportCodes.Add("KRP", "Karup");
            AirportCodes.Add("BBK", "Kasane");
            AirportCodes.Add("KSF", "Kassel");
            AirportCodes.Add("KTM", "Kathmandu - Tribhuvan");
            AirportCodes.Add("KTW", "Katowice");
            AirportCodes.Add("KUN", "Kaunas");
            AirportCodes.Add("KVA", "Kavala-Megas Alexandros Int´l");
            AirportCodes.Add("KZN", "Kazan");
            AirportCodes.Add("EFL", "Kefallinia");
            AirportCodes.Add("KEF", "Keflavik");
            AirportCodes.Add("YLW", "Kelowna");
            AirportCodes.Add("KEM", "Kemi-Tornio");
            AirportCodes.Add("KIR", "Kerry");
            AirportCodes.Add("EYW", "Key West");
            AirportCodes.Add("KHV", "Khabarovsk - Novy");
            AirportCodes.Add("KRT", "Khartoum");
            AirportCodes.Add("KBP", "Kiev - Boryspil State");
            AirportCodes.Add("IEV", "Kiev - Zulhany");
            AirportCodes.Add("KGL", "Kigali");
            AirportCodes.Add("JRO", "Kilimanjaro");
            AirportCodes.Add("KIM", "Kimberley");
            AirportCodes.Add("KIN", "Kingston - Norman Manley");
            AirportCodes.Add("FIH", "Kinshasa-N´Djili");
            AirportCodes.Add("ISO", "Kinston - North Carolina Global Transpark");
            AirportCodes.Add("KKN", "Kirkenes");
            AirportCodes.Add("KOI", "Kirkwall");
            AirportCodes.Add("KRN", "Kiruna");
            AirportCodes.Add("KTT", "Kittilä");
            AirportCodes.Add("KLU", "Klagenfurt");
            AirportCodes.Add("LMT", "Klamath Falls Int´l");
            AirportCodes.Add("NOC", "Knock Int´l");
            AirportCodes.Add("TYS", "Knoxville - McGhee Tyson");
            AirportCodes.Add("KCZ", "Kochi");
            AirportCodes.Add("CCU", "Kolkata - Netaji Subhas Chanra Bose Int´l");
            AirportCodes.Add("KMQ", "Komatsu");
            AirportCodes.Add("FIA", "Kortrijk-Wevelgem/Flanders Int´l");
            AirportCodes.Add("KGS", "Kos - Ippokratis");
            AirportCodes.Add("KSC", "Kosice");
            AirportCodes.Add("KBR", "Kota Bharu - Sultan Ismail Petra");
            AirportCodes.Add("BKI", "Kota Kinabalu Int´l");
            AirportCodes.Add("ACC", "Accra");
            AirportCodes.Add("KRK", "Krakow-Balice");
            AirportCodes.Add("KJA", "Krasnoyarsk");
            AirportCodes.Add("KID", "Kristianstad - Everod");
            AirportCodes.Add("KWG", "Krivij Rig");
            AirportCodes.Add("KOK", "Kruunupyy - Kokkola-Pietarsaari");
            AirportCodes.Add("KUL", "Kuala Lumpur - KLIA");
            AirportCodes.Add("SZB", "Kuala Lumpur - Sultan Abdul Aziz Shah");
            AirportCodes.Add("TGG", "Kuala Terengganu - Sultan Mahmud");
            AirportCodes.Add("KUA", "Kuantan - Sultan Haji Ahmad Shah");
            AirportCodes.Add("KCH", "Kuching Int´l");
            AirportCodes.Add("KMJ", "Kumamoto");
            AirportCodes.Add("KMS", "Kumasi");
            AirportCodes.Add("KMG", "Kunming - Wujiaba");
            AirportCodes.Add("KUO", "Kuopio");
            AirportCodes.Add("URE", "Kuressaare");
            AirportCodes.Add("KAO", "Kuusamo");
            AirportCodes.Add("KWI", "Kuwait");
            AirportCodes.Add("KDL", "Kärdla");
            AirportCodes.Add("LCE", "La Ceiba - Golson");
            AirportCodes.Add("LCG", "La Coruña");
            AirportCodes.Add("LSE", "La Crosse Municipal");
            AirportCodes.Add("HAV", "La Havana - Jose Marti");
            AirportCodes.Add("SPC", "La Palma");
            AirportCodes.Add("LPB", "La Paz-El Alto");
            AirportCodes.Add("LAP", "La Paz-Manuel de Leon");
            AirportCodes.Add("LRH", "La Rochelle - Ile de Ré");
            AirportCodes.Add("EUN", "Laayoune Hassan");
            AirportCodes.Add("LBU", "Labuan");
            AirportCodes.Add("LAE", "Lae");
            AirportCodes.Add("LFT", "Lafayette Regional");
            AirportCodes.Add("LOS", "Lagos - Murtala Muhammed");
            AirportCodes.Add("LDU", "Lahad Datu");
            AirportCodes.Add("LHE", "Lahore - Allama Iqbal");
            AirportCodes.Add("LHA", "Lahr - Black Forest");
            AirportCodes.Add("TVL", "Lake Tahoe");
            AirportCodes.Add("LKL", "Lakselv - Banak");
            AirportCodes.Add("LBQ", "Lambarene");
            AirportCodes.Add("SUF", "Lamezia");
            AirportCodes.Add("LNS", "Lancaster");
            AirportCodes.Add("LGK", "Langkawi");
            AirportCodes.Add("LAI", "Lannion");
            AirportCodes.Add("HLA", "Lanseria");
            AirportCodes.Add("LAN", "Lansing - Capital Airport");
            AirportCodes.Add("ACE", "Lanzarote");
            AirportCodes.Add("LPP", "Lappeenranta");
            AirportCodes.Add("LRD", "Laredo Int´l");
            AirportCodes.Add("LCA", "Larnaca");
            AirportCodes.Add("LAS", "Las Vegas - McCarran");
            AirportCodes.Add("LST", "Launceston");
            AirportCodes.Add("LBG", "Le Bourget");
            AirportCodes.Add("LEH", "Le Havre/Octeville");
            AirportCodes.Add("LTQ", "Le Touquet-Côte d´Opale");
            AirportCodes.Add("LBA", "Leeds Bradford");
            AirportCodes.Add("ABE", "Lehigh Valley");
            AirportCodes.Add("LEJ", "Leipzig/Halle");
            AirportCodes.Add("LEY", "Lelystad");
            AirportCodes.Add("LEX", "Lexington/Blue Grass");
            AirportCodes.Add("LBV", "Libreville-Leon M´Ba Int´l");
            AirportCodes.Add("LPX", "Liepaja");
            AirportCodes.Add("LIH", "Lihue");
            AirportCodes.Add("LIL", "Lille");
            AirportCodes.Add("LLW", "Lilongwe");
            AirportCodes.Add("CLX", "Lima - Jorge Chavez");
            AirportCodes.Add("LXS", "Limnos");
            AirportCodes.Add("LIG", "Limoges/Bellegarde");
            AirportCodes.Add("LMH", "Limon");
            AirportCodes.Add("LNZ", "Linz - Blue Danube");
            AirportCodes.Add("LIS", "Lisbon");
            AirportCodes.Add("LIT", "Little Rock National");
            AirportCodes.Add("LPL", "Liverpool - John Lennon");
            AirportCodes.Add("LVI", "Livingstone");
            AirportCodes.Add("LGG", "Liège");
            AirportCodes.Add("LJU", "Ljubljana D D");
            AirportCodes.Add("MDZ", "Ljubljana D Dndoza-El Plumerillo");
            AirportCodes.Add("LFW", "Lome-Tokoin");
            AirportCodes.Add("BQH", "London - Biggin Hill");
            AirportCodes.Add("LCY", "London - Airport");
            AirportCodes.Add("LGW", "London - Gatwick");
            AirportCodes.Add("LHR", "London - Heathrow");
            AirportCodes.Add("LTN", "London - Luton");
            AirportCodes.Add("MSE", "London - Manston");
            AirportCodes.Add("SEN", "London - Southend");
            AirportCodes.Add("STN", "London - Stansted");
            AirportCodes.Add("LGB", "Long Beach");
            AirportCodes.Add("ISP", "Long Island - MacArthur");
            AirportCodes.Add("LPR", "Lorain County Regional");
            AirportCodes.Add("LRT", "Lorient/Lann-Bihoué");
            AirportCodes.Add("LAX", "Los Angeles");
            AirportCodes.Add("SDF", "Louisville");
            AirportCodes.Add("LAD", "Luanda - 4 de Fevereiro");
            AirportCodes.Add("LBB", "Lubbock");
            AirportCodes.Add("LKO", "Lucknow - Amausi");
            AirportCodes.Add("LBC", "Luebeck - Blankensee");
            AirportCodes.Add("LUG", "Lugano");
            AirportCodes.Add("LLA", "Luleå-Kallax Cargo");
            AirportCodes.Add("LUN", "Lusaka");
            AirportCodes.Add("LUX", "Luxembourg-Findel");
            AirportCodes.Add("LXR", "Luxor");
            AirportCodes.Add("LYX", "Lydd");
            AirportCodes.Add("LYH", "Lynchburg Regional");
            AirportCodes.Add("LYS", "Lyon");
            AirportCodes.Add("MST", "Maastricht Aachen");
            AirportCodes.Add("MFM", "Macau");
            AirportCodes.Add("MKY", "Mackay");
            AirportCodes.Add("NOP", "Mactan - Cebu Int´l");
            AirportCodes.Add("MAD", "Madrid - Barajas");
            AirportCodes.Add("MCV", "Madrid - Cuatro Vientos");
            AirportCodes.Add("GDX", "Magadan Sokol");
            AirportCodes.Add("SKG", "Makedonia-Thessaloniki");
            AirportCodes.Add("SSG", "Malabo");
            AirportCodes.Add("AGP", "Malaga");
            AirportCodes.Add("MLE", "Male");
            AirportCodes.Add("MMX", "Malmö - Sturup");
            AirportCodes.Add("MLA", "Malta Int´l");
            AirportCodes.Add("MDC", "Manado - Sam Ratulangi");
            AirportCodes.Add("MGA", "Managua - Augusto Cesar Sandino");
            AirportCodes.Add("MAO", "Manaus-Eduardo Gomes Int´l");
            AirportCodes.Add("MHT", "Manchester");
            AirportCodes.Add("MAN", "Manchester");
            AirportCodes.Add("MDL", "Mandalay");
            AirportCodes.Add("MNL", "Manila - Ninoy Aquino Int´l");
            AirportCodes.Add("MZO", "Manzanillo-Sierra Maestra Int´l");
            AirportCodes.Add("MPM", "Maputo");
            AirportCodes.Add("MTH", "Marathon");
            AirportCodes.Add("MBX", "Maribor Aerodrom");
            AirportCodes.Add("MHQ", "Mariehamn");
            AirportCodes.Add("RAK", "Marrakech - Menara");
            AirportCodes.Add("MRS", "Marseille/Provence");
            AirportCodes.Add("FDF", "Martinique-Lamentin");
            AirportCodes.Add("MSU", "Maseru-Moshoeshoe 1");
            AirportCodes.Add("MCW", "Mason Airport Municipal");
            AirportCodes.Add("MAM", "Matamoros - General Servando Canales");
            AirportCodes.Add("MTS", "Matsapha");
            AirportCodes.Add("MMJ", "Matsumoto");
            AirportCodes.Add("MUB", "Maun");
            AirportCodes.Add("MZT", "Mazatlan - General Rafael Buelna");
            AirportCodes.Add("MDK", "Mbandaka");
            AirportCodes.Add("MFE", "McAllen - Miller");
            AirportCodes.Add("MES", "Medan-Polonia");
            AirportCodes.Add("MDE", "Medellin - Jose Maria Cordova");
            AirportCodes.Add("MKZ", "Melaka - Batu Berendam");
            AirportCodes.Add("MLB", "Melbourne Int´l");
            AirportCodes.Add("MEL", "Melbourne - Tullamarine");
            AirportCodes.Add("MLN", "Melilla");
            AirportCodes.Add("MLZ", "Melo - Aeropuerto Int´l de Cerro Largo");
            AirportCodes.Add("DOM", "Melville Hall");
            AirportCodes.Add("MEM", "Memphis");
            AirportCodes.Add("MAH", "Menorca");
            AirportCodes.Add("PSE", "Mercedita");
            AirportCodes.Add("MID", "Merida - Licenciado Manuel Crecencio Rejon Int´l");
            AirportCodes.Add("MEI", "Meridian Regional-Key Field");
            AirportCodes.Add("ETZ", "Metz/Nancy/Lorraine");
            AirportCodes.Add("MEX", "Mexico-Benito Juarez");
            AirportCodes.Add("MIA", "Miami");
            AirportCodes.Add("MAF", "Midland");
            AirportCodes.Add("MIK", "Mikkeli Airport");
            AirportCodes.Add("BGY", "Milan - Orio Al Serio");
            AirportCodes.Add("LIN", "Milan-Linate");
            AirportCodes.Add("MXP", "Milan-Malpensa");
            AirportCodes.Add("MKE", "Milwaukee - General Mitchell Int´l");
            AirportCodes.Add("MSP", "Minneapolis-St Paul Int´l");
            AirportCodes.Add("MOT", "Minot");
            AirportCodes.Add("MSQ", "Minsk National");
            AirportCodes.Add("MYY", "Miri");
            AirportCodes.Add("MSJ", "Misawa");
            AirportCodes.Add("MSO", "Missoula Int´l - Johnson-Bell Field");
            AirportCodes.Add("MJT", "Mitilini");
            AirportCodes.Add("BFM", "Mobile Downtown");
            AirportCodes.Add("MOB", "Mobile Regional");
            AirportCodes.Add("MOD", "Modesto Airport County");
            AirportCodes.Add("MGQ", "Mogadishu");
            AirportCodes.Add("MOL", "Molde-Aaro");
            AirportCodes.Add("MBA", "Mombasa - Moi Int´l");
            AirportCodes.Add("MCM", "Monaco Heliport");
            AirportCodes.Add("YQM", "Moncton");
            AirportCodes.Add("ROB", "Monrovia-Roberts");
            AirportCodes.Add("MBJ", "Montego Bay - Sangster");
            AirportCodes.Add("MTY", "Monterrey");
            AirportCodes.Add("MUD", "Montevideo - Carrasco");
            AirportCodes.Add("MPL", "Montpellier - Mediterranée Aéroport");
            AirportCodes.Add("YMX", "Montréal-Mirabel");
            AirportCodes.Add("YUL", "Montréal-Pierre Elliott Trudeau");
            AirportCodes.Add("MNI", "Montserrat");
            AirportCodes.Add("MBW", "Moorabbin");
            AirportCodes.Add("MXX", "Mora - Siljan");
            AirportCodes.Add("DME", "Moscow - Domodedovo");
            AirportCodes.Add("SVO", "Moscow - Sheremetyevo");
            AirportCodes.Add("VKO", "Moscow - Vnukovo");
            AirportCodes.Add("OMO", "Mostar");
            AirportCodes.Add("ISA", "Mount Isa");
            AirportCodes.Add("BOM", "Mumbai/Bombay - Chhatarpati Shivaji");
            AirportCodes.Add("MUC", "Munich");
            AirportCodes.Add("MMK", "Murmansk");
            AirportCodes.Add("MCT", "Muscat-Seeb");
            AirportCodes.Add("MSR", "Münster-Osnabrück");
            AirportCodes.Add("NGO", "Nagoya");
            AirportCodes.Add("NBO", "Nairobi - Jomo Kenyatta");
            AirportCodes.Add("APL", "Nampula");
            AirportCodes.Add("ENC", "Nancy/Essey Aéroport");
            AirportCodes.Add("NKG", "Nanjing Lukou Co Ltd");
            AirportCodes.Add("NTE", "Nantes-Atlantique");
            AirportCodes.Add("ACK", "Nantucket Memorial");
            AirportCodes.Add("APF", "Naples Municipal");
            AirportCodes.Add("NAP", "Naples-Capodichino");
            AirportCodes.Add("UAK", "Narssarssuaq");
            AirportCodes.Add("BNA", "Nashville");
            AirportCodes.Add("NAS", "Nassau");
            AirportCodes.Add("NAT", "Natal - Augusto Severo");
            AirportCodes.Add("INU", "Nauru");
            AirportCodes.Add("NLA", "Ndola and Kitwe");
            AirportCodes.Add("NEV", "Nevis - Newcastle");
            AirportCodes.Add("NOU", "New Caledonia");
            AirportCodes.Add("HVN", "New Haven");
            AirportCodes.Add("MSY", "New Orleans - Louis Armstrong");
            AirportCodes.Add("JFK", "New York - John F Kennedy");
            AirportCodes.Add("LGA", "New York-La Guardia");
            AirportCodes.Add("EWR", "Newark");
            AirportCodes.Add("NTL", "Newcastle");
            AirportCodes.Add("NCL", "Newcastle");
            AirportCodes.Add("NQY", "Newquay Cornwall");
            AirportCodes.Add("NIM", "Niamey Diori Hamani");
            AirportCodes.Add("NCE", "Nice/Cote D´Azur");
            AirportCodes.Add("KIJ", "Niigata");
            AirportCodes.Add("FNI", "Nimes/Arles/Camargue");
            AirportCodes.Add("NOG", "Nogales");
            AirportCodes.Add("ORF", "Norfolk");
            AirportCodes.Add("NRK", "Norrköping");
            AirportCodes.Add("LBF", "North Platte Regional");
            AirportCodes.Add("PQI", "Northern Maine Regional");
            AirportCodes.Add("NWI", "Norwich");
            AirportCodes.Add("NDB", "Nouadhibou Aerodrome");
            AirportCodes.Add("NKO", "Nouakchott Aerodrome");
            AirportCodes.Add("OVB", "Novosibirsk Tolmachevo");
            AirportCodes.Add("NLD", "Nuevo Laredo - Quetzalcoatl");
            AirportCodes.Add("NUE", "Nuremberg");
            AirportCodes.Add("NDH", "N´Djamena");
            AirportCodes.Add("OAK", "Oakland");
            AirportCodes.Add("OAX", "Oaxaca");
            AirportCodes.Add("ODE", "Odense");
            AirportCodes.Add("ODS", "Odessa");
            AirportCodes.Add("OHD", "Ohrid");
            AirportCodes.Add("OKJ", "Okayama");
            AirportCodes.Add("OKA", "Okinawa/Naha");
            AirportCodes.Add("OKC", "Oklahoma Airport-Will Rogers World");
            AirportCodes.Add("OLB", "Olbia-Costa Smerelda");
            AirportCodes.Add("OMA", "Omaha-Eppley Airfield");
            AirportCodes.Add("ONT", "Ontario Int´l");
            AirportCodes.Add("OPO", "Oporto - Fr SA Carneiro");
            AirportCodes.Add("EOI", "Orkney Is - Eday Airstrip");
            AirportCodes.Add("NRL", "Orkney Is - N Ronaldsay Airstrip");
            AirportCodes.Add("MCO", "Orlando");
            AirportCodes.Add("SFB", "Orlando/Sanford Central Florida Regional");
            AirportCodes.Add("ITM", "Osaka - Itami");
            AirportCodes.Add("KIX", "Osaka - Kansai Co Ltd");
            AirportCodes.Add("GEN", "Oslo - Gardermoen");
            AirportCodes.Add("OST", "Ostend");
            AirportCodes.Add("OSR", "Ostrava Int´l");
            AirportCodes.Add("YOW", "Ottawa");
            AirportCodes.Add("OUA", "Ouagadougou");
            AirportCodes.Add("OZZ", "Ouarzazate");
            AirportCodes.Add("OUD", "Oujda Angads");
            AirportCodes.Add("OUL", "Oulu");
            AirportCodes.Add("OXF", "Oxford");
            AirportCodes.Add("PAD", "Paderborn/Lippstadt");
            AirportCodes.Add("PPG", "Pago Pago");
            AirportCodes.Add("PLQ", "Palanga");
            AirportCodes.Add("PLM", "Palembang - Sultan Mahmud Badaruddin II");
            AirportCodes.Add("PMO", "Palermo -o Falcone e Borsellino");
            AirportCodes.Add("PBI", "Palm Beach Int´l");
            AirportCodes.Add("PSP", "Palm Springs Regional");
            AirportCodes.Add("PMI", "Palma De Mallorca");
            AirportCodes.Add("PNA", "Pamplona");
            AirportCodes.Add("PTY", "Panama Airport-Tocumen");
            AirportCodes.Add("PFN", "Panama Airport/Bay County Int´l");
            AirportCodes.Add("PFO", "Paphos");
            AirportCodes.Add("PBM", "Paramaribo - Johan Adolf Pengel Int´l");
            AirportCodes.Add("PED", "Pardubice");
            AirportCodes.Add("CDG", "Paris - Charles De Gaulle");
            AirportCodes.Add("ORY", "Paris - Orly");
            AirportCodes.Add("POX", "Paris - Pontoise");
            AirportCodes.Add("PKB", "Parkersburg - Mid-Ohio Valley Regional");
            AirportCodes.Add("PBH", "Paro");
            AirportCodes.Add("PAT", "Patna");
            AirportCodes.Add("GPA", "Patras/Araxos National");
            AirportCodes.Add("PUF", "Pau - Pyrenees");
            AirportCodes.Add("PEN", "Penang");
            AirportCodes.Add("PDT", "Pendleton/Eastern Oregon Regional");
            AirportCodes.Add("PNS", "Pensacola");
            AirportCodes.Add("PZE", "Penzance Heliport");
            AirportCodes.Add("PIA", "Peoria - Greater Peoria Regional");
            AirportCodes.Add("PEI", "Pereira-Matecana");
            AirportCodes.Add("PGF", "Perpignan/Rivesaltes");
            AirportCodes.Add("PER", "Perth Int´l - Westralia Corporation");
            AirportCodes.Add("PEW", "Peshawar");
            AirportCodes.Add("PKC", "Petropavlovsk-Kamchatsky - Yelizovo");
            AirportCodes.Add("PHL", "Philadelphia");
            AirportCodes.Add("PNH", "Phnom Penh");
            AirportCodes.Add("PHX", "Phoenix Sky Harbor Int´l");
            AirportCodes.Add("HKT", "Phuket Int´l");
            AirportCodes.Add("POS", "Piarco");
            AirportCodes.Add("GSO", "Piedmont Triad Int´l");
            AirportCodes.Add("PZY", "Piestany");
            AirportCodes.Add("NTY", "Pilanesburg");
            AirportCodes.Add("PSA", "Pisa");
            AirportCodes.Add("DTP", "Pittsburgh");
            AirportCodes.Add("PIU", "Piura");
            AirportCodes.Add("PLB", "Plattsburgh Clinton County");
            AirportCodes.Add("PBG", "Plattsburgh Int´l AFB");
            AirportCodes.Add("PDV", "Plovdiv");
            AirportCodes.Add("PLH", "Plymouth Airport");
            AirportCodes.Add("PTP", "Point-a-Pitre Le Raizet");
            AirportCodes.Add("PNR", "Pointe - Noire Aerodrome");
            AirportCodes.Add("PIS", "Poitiers - Biard");
            AirportCodes.Add("PMG", "Ponta Pora Int´l");
            AirportCodes.Add("PNK", "Pontianak - Supadio");
            AirportCodes.Add("TAT", "Poprad-Tatry");
            AirportCodes.Add("POR", "Pori");
            AirportCodes.Add("CLM", "Port Angeles-William R Fairchild Int´l");
            AirportCodes.Add("PLZ", "Port Elizabeth");
            AirportCodes.Add("POG", "Port Gentil");
            AirportCodes.Add("PHC", "Port Harcourt");
            AirportCodes.Add("POM", "Port Moresby/Jacksons");
            AirportCodes.Add("VLI", "Port Vila - Bauerfield");
            AirportCodes.Add("PAP", "Port-au-Prince");
            AirportCodes.Add("PDX", "Portland");
            AirportCodes.Add("POA", "Porto Alegre - Salgado Filho Int´l");
            AirportCodes.Add("PXO", "Porto Santo");
            AirportCodes.Add("POU", "Poughkeepsie - Dutchess County");
            AirportCodes.Add("PAZ", "Poza Rica - Tajin");
            AirportCodes.Add("POZ", "Poznan-Lawica");
            AirportCodes.Add("PRG", "Prague-Ruzyne");
            AirportCodes.Add("YXS", "Prince George");
            AirportCodes.Add("PVD", "Providence-Theodore Francis Green");
            AirportCodes.Add("PLS", "Providenciales");
            AirportCodes.Add("PNN", "Provincetown Municipal");
            AirportCodes.Add("PBC", "Puebla - Hermanos Serdan");
            AirportCodes.Add("PMC", "Puerto Montt-El Tepual");
            AirportCodes.Add("POP", "Puerto Plata");
            AirportCodes.Add("PVR", "Puerto Vallarta Int´l - Gustavo Diaz Ordaz");
            AirportCodes.Add("PUY", "Pula");
            AirportCodes.Add("PUQ", "Punta Arenas");
            AirportCodes.Add("FNJ", "P´yongyang-Sunan");
            AirportCodes.Add("QRO", "Querétaro - Ingeniero F Espinoza Gutierrez Int´l");
            AirportCodes.Add("UIP", "Quimper - Pluguffan");
            AirportCodes.Add("UIO", "Quito-Mariscal Sucre");
            AirportCodes.Add("YQB", "Québec");
            AirportCodes.Add("RBA", "Rabat-Sale");
            AirportCodes.Add("RAB", "Rabaul-Lakunai");
            AirportCodes.Add("RAH", "Rafha");
            AirportCodes.Add("RDU", "Raleigh - Durham Int´l");
            AirportCodes.Add("RAP", "Rapid Airport Regional");
            AirportCodes.Add("RKT", "Ras Al Khaimah");
            AirportCodes.Add("RDG", "Reading Regional");
            AirportCodes.Add("REC", "Recife - Guararapes/Gilberto Freyre Int´l");
            AirportCodes.Add("RDM", "Redmond Municipal - Roberts Field");
            AirportCodes.Add("RHE", "Reims/Champagne");
            AirportCodes.Add("RNS", "Rennes/Saint-Jacques");
            AirportCodes.Add("RNO", "Reno/Tahoe");
            AirportCodes.Add("REU", "Reus");
            AirportCodes.Add("REK", "Reykjavik");
            AirportCodes.Add("RHI", "Rhinelander - Oneida County");
            AirportCodes.Add("RHQ", "Rhodes-Diagoras");
            AirportCodes.Add("RIC", "Richmond");
            AirportCodes.Add("LCK", "Rickenbacker");
            AirportCodes.Add("RIX", "Riga");
            AirportCodes.Add("RJK", "Rijeka-Riviera Kvarner");
            AirportCodes.Add("RMI", "Rimini - Miramareo");
            AirportCodes.Add("RBR", "Rio Branco - Presidente Medici");
            AirportCodes.Add("GIG", "Rio De Janeiro");
            AirportCodes.Add("RUH", "Riyadh - King Khaled");
            AirportCodes.Add("ROA", "Roanoke Regional");
            AirportCodes.Add("RST", "Rochester");
            AirportCodes.Add("RSD", "Rock Sound");
            AirportCodes.Add("RWI", "Rocky Mount/Wilson Regional");
            AirportCodes.Add("RDZ", "Rodez/Marcillac");
            AirportCodes.Add("RUN", "Roland Garros");
            AirportCodes.Add("CIA", "Rome - Ciampino");
            AirportCodes.Add("FCO", "Rome-Leonardo da Vinci Fiumicino");
            AirportCodes.Add("RPN", "Rosh Pina - Mahanaim Ben Yaakov");
            AirportCodes.Add("ROW", "Roswell Industrial Air Center");
            AirportCodes.Add("RTM", "Rotterdam");
            AirportCodes.Add("RVN", "Rovaniemi");
            AirportCodes.Add("RZE", "Rzeszow-Jasionka");
            AirportCodes.Add("SCN", "Saarbrucken");
            AirportCodes.Add("QSA", "Sabadell");
            AirportCodes.Add("SMF", "Sacramento County System");
            AirportCodes.Add("SBK", "Saint Brieuc-Armor");
            AirportCodes.Add("STX", "Saint Croix - Henry E Rohlsen");
            AirportCodes.Add("EBU", "Saint Etienne/Boutheon");
            AirportCodes.Add("SKB", "Saint Kitts - Robert Bradshaw");
            AirportCodes.Add("STL", "Saint Louis - Lambert Int´l");
            AirportCodes.Add("UVW", "Saint Lucia - Hewanorra");
            AirportCodes.Add("SLU", "Saint Lucia-Vigie");
            AirportCodes.Add("SXM", "Saint Maarten-Princess Juliana");
            AirportCodes.Add("STT", "Saint Thomas-Cyril E King");
            AirportCodes.Add("SVD", "Saint Vincent-E T Joshua");
            AirportCodes.Add("SPN", "Saipan");
            AirportCodes.Add("SLL", "Salalah");
            AirportCodes.Add("SLM", "Salamanca");
            AirportCodes.Add("SLN", "Salina");
            AirportCodes.Add("SBY", "Salisbury/Ocean Airport Regional");
            AirportCodes.Add("SLC", "Salt Lake Airport");
            AirportCodes.Add("SLA", "Salta");
            AirportCodes.Add("SZG", "Salzburg - W A Mozart");
            AirportCodes.Add("SKD", "Samarkand");
            AirportCodes.Add("SMI", "Samos");
            AirportCodes.Add("ADZ", "San Andres - Gustavo Rojas Pinilla");
            AirportCodes.Add("SJT", "San Angelo Regional/Mathis Field");
            AirportCodes.Add("SAT", "San Antonio");
            AirportCodes.Add("SAN", "San Diego");
            AirportCodes.Add("SFO", "San Francisco");
            AirportCodes.Add("MJV", "San Javier/Murcia");
            AirportCodes.Add("SJC", "San Jose");
            AirportCodes.Add("SJO", "San Jose - Juan Santamaria");
            AirportCodes.Add("SYQ", "San José - Tobias Bolanos");
            AirportCodes.Add("SJU", "San Juan - Luiz Munoz Marin");
            AirportCodes.Add("SBP", "San Luis County Regional");
            AirportCodes.Add("SAP", "San Pedro Sula - La Mesa");
            AirportCodes.Add("EAS", "San Sebastian - Fuenterrabia");
            AirportCodes.Add("SAH", "Sana´a");
            AirportCodes.Add("SDK", "Sandakan");
            AirportCodes.Add("TRF", "Sandefjord - Torp");
            AirportCodes.Add("SNA", "Santa Ana");
            AirportCodes.Add("SMA", "Santa Maria");
            AirportCodes.Add("SDR", "Santander - Parayas");
            AirportCodes.Add("STM", "Santarém Int´l");
            AirportCodes.Add("SCQ", "Santiago");
            AirportCodes.Add("SCU", "Santiago - Antonio Maceo");
            AirportCodes.Add("SCL", "Santiago - Arturo Merino Benitez");
            AirportCodes.Add("SDQ", "Santo Domingo-Las Americas");
            AirportCodes.Add("TMS", "Sao Tome");
            AirportCodes.Add("SJJ", "Sarajevo");
            AirportCodes.Add("SLK", "Saranac Lake-Adirondack Regional");
            AirportCodes.Add("SRQ", "Sarasota Bradenton Int´l");
            AirportCodes.Add("RTW", "Saratov - Tsentralny");
            AirportCodes.Add("YXE", "Saskatoon");
            AirportCodes.Add("SUJ", "Satu Mare");
            AirportCodes.Add("SAV", "Savannah");
            AirportCodes.Add("SVL", "Savonlinna");
            AirportCodes.Add("SEA", "Seattle/Tacoma");
            AirportCodes.Add("SEB", "Sebha");
            AirportCodes.Add("SJY", "Seinäjoki");
            AirportCodes.Add("PKW", "Selebi Phikwe");
            AirportCodes.Add("SDJ", "Sendai");
            AirportCodes.Add("ICN", "Seoul - Incheon");
            AirportCodes.Add("SEL", "Seoul - Kimpo");
            AirportCodes.Add("SVQ", "Seville - San Pablo");
            AirportCodes.Add("SEZ", "Seychelles Int´l");
            AirportCodes.Add("SFA", "Sfax-el-Maou");
            AirportCodes.Add("SHA", "Shanghai - Hong Qiao");
            AirportCodes.Add("PVG", "Shanghai - Pudong");
            AirportCodes.Add("SHN", "Shannon");
            AirportCodes.Add("SHJ", "Sharjah");
            AirportCodes.Add("SZD", "Sheffield Airport");
            AirportCodes.Add("SHE", "Shenyang - Taoxian");
            AirportCodes.Add("SZX", "Shenzhen - Baoan");
            AirportCodes.Add("LSI", "Shetland Island - Sumburgh");
            AirportCodes.Add("SYZ", "Shiraz - Shahid Dastghaib");
            AirportCodes.Add("ESH", "Shoreham");
            AirportCodes.Add("SHV", "Shreveport Regional");
            AirportCodes.Add("SBW", "Sibu");
            AirportCodes.Add("SDY", "Sidney Municipal");
            AirportCodes.Add("SIN", "Singapore - Changi");
            AirportCodes.Add("SIR", "Sion");
            AirportCodes.Add("SUX", "Sioux Gateway");
            AirportCodes.Add("MRU", "Sir Seewoosagur Ramgoolam");
            AirportCodes.Add("SQW", "Skive");
            AirportCodes.Add("SKP", "Skopje");
            AirportCodes.Add("SLD", "Sliac");
            AirportCodes.Add("SXL", "Sligo Regional");
            AirportCodes.Add("SOF", "Sofia EAD");
            AirportCodes.Add("SFJ", "Sondre Stromfjord/Kangerlussuaq");
            AirportCodes.Add("SBN", "South Bend Regional");
            AirportCodes.Add("SLX", "South Caicos");
            AirportCodes.Add("SOU", "Southampton");
            AirportCodes.Add("SPU", "Split");
            AirportCodes.Add("GEG", "Spokane");
            AirportCodes.Add("SGF", "Springfield - Branson Regional");
            AirportCodes.Add("SMV", "St Moritz - Samedan");
            AirportCodes.Add("SNR", "St Nazaire/Montoir");
            AirportCodes.Add("PIE", "St Petersburg-Clearwater Int´l");
            AirportCodes.Add("LED", "St Petersburg-Pulkovo");
            AirportCodes.Add("LTT", "St Tropez du Golfe");
            AirportCodes.Add("YYT", "St. John's");
            AirportCodes.Add("SCE", "State College");
            AirportCodes.Add("STA", "Stauning Vestjyllands");
            AirportCodes.Add("SVG", "Stavanger");
            AirportCodes.Add("SWF", "Stewart");
            AirportCodes.Add("ARN", "Stockholm - Arlanda");
            AirportCodes.Add("BMA", "Stockholm - Bromma");
            AirportCodes.Add("NYO", "Stockholm - Skavsta");
            AirportCodes.Add("SRP", "Stord - Soerstokken");
            AirportCodes.Add("STY", "Stornoway");
            AirportCodes.Add("SXB", "Strasbourg");
            AirportCodes.Add("STR", "Stuttgart");
            AirportCodes.Add("SDL", "Sundsvall-Härnösand");
            AirportCodes.Add("SUB", "Surabaya-Juanda Int´l");
            AirportCodes.Add("SOC", "Surakarta - Adi Sumarmo Wiryokusumo");
            AirportCodes.Add("LYR", "Svalbard-Longyear");
            AirportCodes.Add("SWS", "Swansea");
            AirportCodes.Add("SYD", "Sydney");
            AirportCodes.Add("SYR", "Syracuse - Hancock");
            AirportCodes.Add("SZZ", "Szczecin - Goleniow");
            AirportCodes.Add("CGH", "São Paulo - Congonhas Int´l");
            AirportCodes.Add("SAO", "São Paulo - Guarulhos Int´l");
            AirportCodes.Add("VCP", "São Paulo - Viracopos");
            AirportCodes.Add("SGD", "Sønderborg");
            AirportCodes.Add("TBJ", "Tabarka-7 Novembre Int´l");
            AirportCodes.Add("PPT", "Tahiti - Faa´a");
            AirportCodes.Add("TPE", "Taipei-Chiang Kai Shek");
            AirportCodes.Add("TLL", "Tallinn");
            AirportCodes.Add("TPA", "Tampa Int´l");
            AirportCodes.Add("TMP", "Tampere-Pirkkala");
            AirportCodes.Add("TGT", "Tanga");
            AirportCodes.Add("TNG", "Tangier - Boukhalef");
            AirportCodes.Add("LDE", "Tarbes-Lourdes-Pyrennes");
            AirportCodes.Add("TGM", "Targu Mures");
            AirportCodes.Add("TAY", "Tartu Raadi Ltd");
            AirportCodes.Add("TAS", "Tashkent - Yuzhny");
            AirportCodes.Add("TWU", "Tawau");
            AirportCodes.Add("TBS", "Tbilisi");
            AirportCodes.Add("MME", "Teesside");
            AirportCodes.Add("TGU", "Tegucigalpa-Toncontin");
            AirportCodes.Add("THR", "Tehran - Mehrabad");
            AirportCodes.Add("TCN", "Tehuacán");
            AirportCodes.Add("TLV", "Tel Aviv-Ben Gurion");
            AirportCodes.Add("SDV", "Tel Aviv-Dov Hoz");
            AirportCodes.Add("TFN", "Tenerife North");
            AirportCodes.Add("TFS", "Tenerife South");
            AirportCodes.Add("TCA", "Tennant Creek");
            AirportCodes.Add("TPQ", "Tepic");
            AirportCodes.Add("TRV", "Thiruvanthapuram Int´l");
            AirportCodes.Add("TED", "Thisted");
            AirportCodes.Add("YQT", "Thunder Bay");
            AirportCodes.Add("TSN", "Tianjin - Binhai");
            AirportCodes.Add("TIA", "Tirana - Rinas Mother Teresa");
            AirportCodes.Add("TRE", "Tiree");
            AirportCodes.Add("TRZ", "Tiruchirapalli");
            AirportCodes.Add("HNT", "Tokyo - Haneda Int´l");
            AirportCodes.Add("NRT", "Tokyo-Narita Int´l");
            AirportCodes.Add("TOL", "Toledo Express");
            AirportCodes.Add("TLC", "Toluca - Licenciado Adolfo Lopez Mateos Int´l");
            AirportCodes.Add("YYZ", "Toronto");
            AirportCodes.Add("TLN", "Toulon/Hyeres");
            AirportCodes.Add("TLS", "Toulouse-Blagnac");
            AirportCodes.Add("TSV", "Townsville Int´l");
            AirportCodes.Add("TOY", "Toyama");
            AirportCodes.Add("TOE", "Tozeur - Nefta");
            AirportCodes.Add("TTN", "Trenton - Mercer County");
            AirportCodes.Add("TSF", "Treviso-San Angelo");
            AirportCodes.Add("TRI", "Tri-Airports Regional");
            AirportCodes.Add("TRS", "Trieste - R Dei Legionari");
            AirportCodes.Add("TIP", "Tripoli");
            AirportCodes.Add("TOS", "Tromsø");
            AirportCodes.Add("TRD", "Trondheim/Vaernes");
            AirportCodes.Add("TUS", "Tucson");
            AirportCodes.Add("TCE", "Tulcea");
            AirportCodes.Add("TUL", "Tulsa");
            AirportCodes.Add("TUN", "Tunis - Carthage");
            AirportCodes.Add("TUP", "Tupelo Municipal");
            AirportCodes.Add("TRN", "Turin");
            AirportCodes.Add("TRK", "Turku");
            AirportCodes.Add("TGZ", "Tuxtla Gutiérrez - Francisco Sarabia");
            AirportCodes.Add("TYR", "Tyler Pounds Regional");
            AirportCodes.Add("TJM", "Tyumen - Roshchino");
            AirportCodes.Add("UHE", "Uherské Hradiste - Kunovice");
            AirportCodes.Add("ULN", "Ulan Bator - Buyant Ukha");
            AirportCodes.Add("ULY", "Ulyanovsk-Vostochny");
            AirportCodes.Add("UME", "Umeå");
            AirportCodes.Add("UTN", "Upington");
            AirportCodes.Add("UPN", "Uruapan - Licenciado Y Gen Ignacio Lopez Rayon");
            AirportCodes.Add("URC", "Urumqi - Diwopu");
            AirportCodes.Add("UCA", "Utica - Oneida County");
            AirportCodes.Add("VAA", "Vaasa");
            AirportCodes.Add("FAE", "Vagar");
            AirportCodes.Add("VAF", "Valence/Chabeuil");
            AirportCodes.Add("VLC", "Valencia");
            AirportCodes.Add("VLL", "Valladolid");
            AirportCodes.Add("YVR", "Vancouver");
            AirportCodes.Add("VRA", "Varadero-Juan G Gomez Int´l");
            AirportCodes.Add("VNS", "Varanasi");
            AirportCodes.Add("VRK", "Varkaus");
            AirportCodes.Add("VAR", "Varna Ltd");
            AirportCodes.Add("VCE", "Venice-Aeroporto Marco Polo");
            AirportCodes.Add("VRB", "Vero Beach");
            AirportCodes.Add("VRN", "Verona-Valerio Catullo");
            AirportCodes.Add("VHY", "Vichy/Charmeil");
            AirportCodes.Add("VFA", "Victoria Falls");
            AirportCodes.Add("YYJ", "Victoria, CA");
            AirportCodes.Add("VIE", "Vienna");
            AirportCodes.Add("VTE", "Vientiane - Wattay");
            AirportCodes.Add("VGO", "Vigo");
            AirportCodes.Add("VNO", "Vilnius Int´l");
            AirportCodes.Add("VIJ", "Virgin Gorda");
            AirportCodes.Add("VSE", "Viseu");
            AirportCodes.Add("VIT", "Vitoria Int´l");
            AirportCodes.Add("VVO", "Vladivostok (JSC Vladivostok Air)");
            AirportCodes.Add("SKS", "Vojens - Skrydstrup");
            AirportCodes.Add("VXO", "Växjö - Urasa");
            AirportCodes.Add("WKJ", "Wakkanai");
            AirportCodes.Add("WLS", "Wallis Hihifo");
            AirportCodes.Add("WAW", "Warsaw - Frederic Chopin");
            AirportCodes.Add("IAD", "Washington - Dulles");
            AirportCodes.Add("DCA", "Washington - Ronald Reagan National");
            AirportCodes.Add("WAT", "Waterford Regional");
            AirportCodes.Add("ALO", "Waterloo Municipal");
            AirportCodes.Add("ART", "Watertown Int´l");
            AirportCodes.Add("CWA", "Wausau/Central Wisconsin Regional");
            AirportCodes.Add("WLG", "Wellington");
            AirportCodes.Add("EAT", "Wenatchee/Pangborn Memorial");
            AirportCodes.Add("HPN", "Westchester County");
            AirportCodes.Add("GWT", "Westerland-SFG Sylter Flughafen GmbH & Co");
            AirportCodes.Add("ICT", "Wichita Mid-Continent");
            AirportCodes.Add("WIC", "Wick Aerodrome");
            AirportCodes.Add("WBW", "Wilkes-Barre - Scranton Int´l");
            AirportCodes.Add("IWA", "Williams Gateway");
            AirportCodes.Add("IPT", "Williamsport Regional");
            AirportCodes.Add("ILM", "Wilmington Int´l");
            AirportCodes.Add("WDH", "Windhoek - Hosea Kutako");
            AirportCodes.Add("YQG", "Windsor, CA");
            AirportCodes.Add("YWG", "Winnipeg");
            AirportCodes.Add("INT", "Winston-Salem");
            AirportCodes.Add("ORH", "Worcester Regional");
            AirportCodes.Add("WRO", "Wroclaw-Strachowice");
            AirportCodes.Add("RGN", "Yangon");
            AirportCodes.Add("NSI", "Yaounde-Nsimalen");
            AirportCodes.Add("EVN", "Yerevan-Zvartnots");
            AirportCodes.Add("JOG", "Yogyakarta-Adi Sucipto");
            AirportCodes.Add("UUS", "Yuzhno-Sakhalinsk");
            AirportCodes.Add("OER", "Srnsköldsvik");
            AirportCodes.Add("OSD", "Sstersund");
        }

        public static string GetNameByCode(string code)
        {
            return AirportCodes[code.ToUpper()];
        }
        public static string GetCodeByName(string name)
        {
            var airport = AirportCodes.Where(x => x.Value.ToLower() == name.ToLower()).FirstOrDefault();
            return airport.Key;
        }

        public static Dictionary<string, string> SearchAirports(string keyword)
        {
            return (Dictionary<string, string>)AirportCodes.Where(x => x.Value.ToLower().Contains(keyword.ToLower()) || x.Key.ToLower().Contains(keyword.ToLower()));
        }
    }
    public static class Airlines
    {
        public static Dictionary<string, string> AirlineCodes { get; set; }
    }


    public static class Countries
    {
        //  private static Dictionary<string, string> CityCodes;
        public static Dictionary<string, string> CountryCodes { get; set; }

        public static void InitializeCountries()
        {
            TboService service = new TboService();
            var res = service.Countries();
            CountryCodes = new Dictionary<string, string>();
            foreach (var country in res)
            {
                CountryCodes.Add(country.CountryCode, country.CountryName);
            }
        }

        public static string GetNameByCode(string code)
        {
            return CountryCodes[code.ToUpper()];
        }
        public static string GetCodeByName(string name)
        {
            var city = CountryCodes.Where(x => x.Value.ToLower() == name.ToLower()).FirstOrDefault();
            return city.Key;
        }

        public static Dictionary<string, string> SearchCountries(string keyword)
        {
            return (Dictionary<string, string>)CountryCodes.Where(x => x.Value.ToLower().Contains(keyword.ToLower()) || x.Key.ToLower().Contains(keyword.ToLower()));
        }
    }
}
